# Generated by Django 3.2.6 on 2021-10-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20211008_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_link',
            field=models.URLField(default='#', verbose_name='#'),
            preserve_default=False,
        ),
    ]
